"""empty message

Revision ID: ad0a0ba208cb
Revises: dcef7dca03c0
Create Date: 2020-03-06 04:32:59.681877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad0a0ba208cb'
down_revision = 'dcef7dca03c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('collected_at_source', sa.Integer(), nullable=True),
    sa.Column('advance_paid', sa.Integer(), nullable=True),
    sa.Column('adjustment', sa.Integer(), nullable=True),
    sa.Column('total_tax', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax')
    # ### end Alembic commands ###
