"""empty message

Revision ID: cd32f698bb40
Revises: 
Create Date: 2020-02-22 05:14:32.953535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd32f698bb40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('is_ff', sa.Boolean(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('is_parent_disabled', sa.Boolean(), nullable=False),
    sa.Column('joined_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
