"""empty message

Revision ID: d01da9aeef8b
Revises: 
Create Date: 2020-03-21 10:51:45.981197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd01da9aeef8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('gender', sa.BOOLEAN(), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_ff', sa.BOOLEAN(), nullable=True),
    sa.Column('is_disable', sa.BOOLEAN(), nullable=True),
    sa.Column('is_parent_disable', sa.BOOLEAN(), nullable=True),
    sa.Column('joined_on', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_email_varified', sa.BOOLEAN(), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('income',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('basic', sa.Integer(), nullable=True),
    sa.Column('special', sa.Integer(), server_default='0', nullable=True),
    sa.Column('dearness', sa.Integer(), nullable=True),
    sa.Column('conveyance', sa.Integer(), nullable=True),
    sa.Column('house_rent', sa.Integer(), nullable=True),
    sa.Column('medical', sa.Integer(), nullable=True),
    sa.Column('servant', sa.Integer(), nullable=True),
    sa.Column('leave', sa.Integer(), nullable=True),
    sa.Column('honorarium', sa.Integer(), nullable=True),
    sa.Column('over_time', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('other_allowances', sa.Integer(), nullable=True),
    sa.Column('provident_fund_contrib', sa.Integer(), nullable=True),
    sa.Column('provident_fund_interest', sa.Integer(), nullable=True),
    sa.Column('deemed_transport', sa.Integer(), nullable=True),
    sa.Column('deemed_accomodation_type', sa.BOOLEAN(), nullable=True),
    sa.Column('deemed_accomodation', sa.Integer(), nullable=True),
    sa.Column('other_income_detail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('other_income', sa.Integer(), nullable=True),
    sa.Column('interest_on_securities', sa.Integer(), nullable=True),
    sa.Column('agricultural_income', sa.Integer(), nullable=True),
    sa.Column('capital_gains', sa.Integer(), nullable=True),
    sa.Column('property_description', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('annual_rental_income', sa.Integer(), nullable=True),
    sa.Column('repair_expense', sa.Integer(), nullable=True),
    sa.Column('municipal_tax', sa.Integer(), nullable=True),
    sa.Column('land_revenue', sa.Integer(), nullable=True),
    sa.Column('interest_on_loan', sa.Integer(), nullable=True),
    sa.Column('insurance_premium', sa.Integer(), nullable=True),
    sa.Column('vacancy_allowance', sa.Integer(), nullable=True),
    sa.Column('other_expense', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('life_insurance', sa.Integer(), nullable=True),
    sa.Column('deferred_contrib', sa.Integer(), nullable=True),
    sa.Column('provident_contrib', sa.Integer(), nullable=True),
    sa.Column('employers_provident_contrib', sa.Integer(), nullable=True),
    sa.Column('super_annuation_contrib', sa.Integer(), nullable=True),
    sa.Column('debenture_invest', sa.Integer(), nullable=True),
    sa.Column('deposit_pension_contrib', sa.Integer(), nullable=True),
    sa.Column('benevolent_fund_contrib', sa.Integer(), nullable=True),
    sa.Column('zakat_fund_contrib', sa.Integer(), nullable=True),
    sa.Column('other_investment_detail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('other_investment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('collected_at_source', sa.Integer(), nullable=True),
    sa.Column('advance_paid', sa.Integer(), nullable=True),
    sa.Column('adjustment', sa.Integer(), nullable=True),
    sa.Column('total_tax', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax')
    op.drop_table('investment')
    op.drop_table('income')
    op.drop_table('user')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
