"""empty message

Revision ID: dcef7dca03c0
Revises: 3a573cfa03cb
Create Date: 2020-03-06 03:42:18.618524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcef7dca03c0'
down_revision = '3a573cfa03cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('life_insurance', sa.Integer(), nullable=True),
    sa.Column('deferred_contrib', sa.Integer(), nullable=True),
    sa.Column('provident_contrib', sa.Integer(), nullable=True),
    sa.Column('employers_provident_contrib', sa.Integer(), nullable=True),
    sa.Column('super_annuation_contrib', sa.Integer(), nullable=True),
    sa.Column('debenture_invest', sa.Integer(), nullable=True),
    sa.Column('deposit_pension_contrib', sa.Integer(), nullable=True),
    sa.Column('benevolent_fund_contrib', sa.Integer(), nullable=True),
    sa.Column('zakat_fund_contrib', sa.Integer(), nullable=True),
    sa.Column('other_investment_detail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('other_investment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment')
    # ### end Alembic commands ###
